name: Backend Continuous Integration

# Ensure the workflow
on:
    workflow_dispatch:
    pull_request:
        branches:
        - main


# Jobs defined in the workflow
jobs:
    linting:
      runs-on: ubuntu-latest
      steps:
        - name: Checkout code
          uses: actions/checkout@v3
  
        - name: Set up Python 3
          uses: actions/setup-python@v4
          with:
            python-version: "3.10"
            

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pipenv
            pip install flake8
  
        - name: Run the lint check
          run: cd starter/backend && pipenv run lint
            
  
    testing:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.10' 

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install pipenv
            pipenv install --dev

        - name: Run the Test check
          run: | 
            cd starter/backend
            pipenv install pytest
            pipenv run test
          
          
    build-actions:
      needs: [linting, testing]
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3

        - name: Build the Docker image
          run: | 
            cd starter/backend
            docker build --tag mp-backend:latest .
    
